# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'WLTest' do
  use_frameworks!

  # Pods for WLTest
  pod 'Alamofire', '4.7'
  pod 'RealmSwift'
  pod 'Swinject' 

  target 'WLTests' do
      inherit! :search_paths
      pod 'Alamofire', '4.7'
  end


end
